### PR TITLE
fix(#932): warn before opening a WebView when a site proxy is configured

### LINKED ISSUE #932: proxy not working in webview

### PR DESCRIPTION
**Pull request by jim-daf**
## Warn before opening a WebView when a proxy is configured (refs #932)

Resolves #932

### Background

The Android `WebView` does not honor the proxies that Kuroba routes its OkHttp traffic through. If a user configures a proxy for a site to hide their IP, then taps a link that opens in the in app WebView, the WebView connects directly and the destination sees the real IP.

### What this PR does

When `OpenUrlInWebViewController` is about to load a URL, it checks `ProxyStorage.getProxyByUri(...)` for a proxy configured for that site. If a proxy is configured, it shows a confirmation dialog before loading. The user can choose to open anyway or cancel.

### Implementation notes

- Uses `dialogFactory.showDialog` with `KurobaComposeDialogController.confirmationDialog`. The positive button is marked `isActionDangerous` because opening anyway is the risky action.
- If `showDialog` returns null (app not in foreground), we just pop the controller. No leak.
- Awaits the button click via `params.awaitButtonClick()`, so no manual `suspendCancellableCoroutine` glue.

### Strings added

```
open_url_in_webview_proxy_leak_title
open_url_in_webview_proxy_leak_description
open_url_in_webview_proxy_leak_open_anyway
```

### Files changed

- `Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt`
- `Kuroba/app/src/main/res/values/strings.xml`

### CODE REVIEW

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 1]
```diff
@@ -87,6 +93,25 @@ class OpenUrlInWebViewController(
...
+    val proxiesForUrl = try {
+      proxyStorage.getProxyByUri(URI(urlToOpen.toString()), ProxyStorage.ProxyActionType.SiteRequests)
+    } catch (_: Throwable) {
+      emptyList()
+    }
+    if (proxiesForUrl.isNotEmpty()) {
+      Logger.warning(TAG) {
+        "Refusing to open WebView for ${urlToOpen}: a proxy is configured for this site (issue #932)"
+      }
+      showToast(context, R.string.open_url_in_webview_proxy_leak_blocked)
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: I think maybe it would be better to ask the user if he wants to open the url? Right now it will always prevent the user from opening it which might not be ideal.

Comment (jim-daf) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: Good call. I switched it to a confirmation dialog instead of a hard block. When a proxy is configured for the target site the controller now shows a dialog explaining that the WebView would bypass the proxy and reveal the device IP, with `Open anyway` and `Cancel` buttons. If the user picks `Open anyway` the WebView loads as before, otherwise the controller pops without loading the URL. Default action is cancel so a stray tap does not leak the IP, but the user is still in control. I added `DialogFactory` as an injected dependency for this and dropped the toast path. The PR description and commit message have been updated to match. New string resources for the dialog text are referenced as `open_url_in_webview_proxy_leak_title`, `open_url_in_webview_proxy_leak_description`, and `open_url_in_webview_proxy_leak_open_anyway` so you can name and translate them as you prefer.

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 2]
```diff
@@ -96,20 +100,44 @@ class OpenUrlInWebViewController(
...
     } catch (_: Throwable) {
       emptyList()
     }
     if (proxiesForUrl.isNotEmpty()) {
       Logger.warning(TAG) {
-        "Refusing to open WebView for ${urlToOpen}: a proxy is configured for this site (issue #932)"
+        "WebView for ${urlToOpen} would bypass the proxy configured for this site (issue #932)"
+      }
+      val openAnyway = suspendCancellableCoroutine<Boolean> { cont ->
+        var resumed = false
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: This is not needed, `resumeValueSafe` already checks internally whether or not a continuation is active or not.

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 3]
```diff
@@ -96,20 +100,44 @@ class OpenUrlInWebViewController(
...
+        fun resumeOnce(value: Boolean) {
+          if (resumed) {
+            return
+          }
+          resumed = true
+          cont.resumeValueSafe(value)
+        }
+        val handle = dialogFactory.createSimpleConfirmationDialog(
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: Please use `showDialog` instead. `createSimpleConfirmationDialog` is deprecated. You can even use `Params.awaitButtonClick() == ClickedButton.Primary` and remove `suspendCancellableCoroutine`

**Comment by K1rakishou** [comment]
Also, these strings are missing from strings.xml:
```
open_url_in_webview_proxy_leak_title
open_url_in_webview_proxy_leak_description
open_url_in_webview_proxy_leak_open_anyway
```

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt (hunk 2 above)
Comment (jim-daf) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: Done. Removed the `resumed` flag and the local `resumeOnce` helper. The new code uses `params.awaitButtonClick()` from `KurobaComposeDialogController.Params`, so the manual continuation is gone entirely.

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt (hunk 3 above)
Comment (jim-daf) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: Done. Switched to `dialogFactory.showDialog(...)` with `KurobaComposeDialogController.confirmationDialog(...)` and `params.awaitButtonClick()?.isPositive() == true`. The `suspendCancellableCoroutine` wrapper is removed. The positive button is marked `isActionDangerous` since opening anyway is the risky choice.

**Comment by jim-daf** [comment]
@K1rakishou regarding:

> Also, these strings are missing from strings.xml:
> ```
> open_url_in_webview_proxy_leak_title
> open_url_in_webview_proxy_leak_description
> open_url_in_webview_proxy_leak_open_anyway
> ```

Added the three missing entries to `Kuroba/app/src/main/res/values/strings.xml` in the latest commit:

- `open_url_in_webview_proxy_leak_title`
- `open_url_in_webview_proxy_leak_description`
- `open_url_in_webview_proxy_leak_open_anyway`

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 4]
```diff
@@ -37,6 +41,12 @@ class OpenUrlInWebViewController(
   @Inject
   lateinit var themeEngine: ThemeEngine
 
+  @Inject
+  lateinit var proxyStorage: ProxyStorage
+
+  @Inject
+  lateinit var dialogFactory: DialogFactory
```
Comment (K1rakishou) [inline Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: The compilation fails right now because `Controller` is already defined in a base class. You can just remove this:
```
@Inject
  lateinit var dialogFactory: DialogFactory
```

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 5]
```diff
@@ -87,6 +93,25 @@ class OpenUrlInWebViewController(
...
   @SuppressLint("SetJavaScriptEnabled")
   private suspend fun onCreateInternal() {
+    // Issue #932: the Android WebView does not honor the proxies that
+    // Kuroba routes its OkHttp traffic through. If a proxy is configured
+    // for the site we are about to open, loading the URL in the WebView
+    // would bypass that proxy and reveal the device IP. Refuse to open
+    // the WebView in that case so the user is not silently de-anonymized.
+    val proxiesForUrl = try {
+      proxyStorage.getProxyByUri(URI(urlToOpen.toString()), ProxyStorage.ProxyActionType.SiteRequests)
+    } catch (_: Throwable) {
```
[the remark this answers is not in the document]
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt:103]: Yeah, I think you could wrap it in `withContext(Dispatchers.Default)` so that it doesn't introduce micro-freezes when this controller is opened, like this: 
```
withContext(Dispatchers.Default) {
    proxyStorage.getProxyByUri(URI(urlToOpen.toString()), ProxyStorage.ProxyActionType.SiteRequests)
}
```

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt [hunk 6]
```diff
@@ -87,6 +93,25 @@ class OpenUrlInWebViewController(
...
+      emptyList()
+    }
```
[the remark this answers is not in the document]
Comment (K1rakishou) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt:105]: This is probably not super critical here.

File: Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt (hunk 4 above)
Comment (jim-daf) [reply Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt]: I removed the duplicate injection line from OpenUrlInWebViewController. The controller now uses the inherited dialogFactory from the base class while keeping the proxyStorage injection which is specific to this controller. The fix has been pushed to the fork and is ready for testing.

**Comment by K1rakishou** [comment]
I think you accidentally merged this MR into the current one: https://github.com/K1rakishou/Kuroba-Experimental/pull/1135 I see the changes to waiters.

Other than that there is only this linter warning left:
```
/home/runner/work/Kuroba-Experimental/Kuroba-Experimental/Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt:14:2: Unused import [NoUnusedImports]
```
Just remove this unused import and it should pass.

**Comment by jim-daf** [comment]
> I think you accidentally merged this MR into the current one: #1135 I see the changes to waiters.
> 
> Other than that there is only this linter warning left:
> 
> ```
> /home/runner/work/Kuroba-Experimental/Kuroba-Experimental/Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/controller/OpenUrlInWebViewController.kt:14:2: Unused import [NoUnusedImports]
> ```
> 
> Just remove this unused import and it should pass.

Sorry about that. I rebased the branch onto the current develop tip so the PR now contains only the two files relevant to this change.

* OpenUrlInWebViewController.kt (proxy check and warning dialog)
* strings.xml (three new strings)

The unused DialogFactory import is gone, dialogFactory comes from the parent class. No more changes to SuspendableInitializer or SiteResolver in this PR, and the PR shows no merge conflicts.

**Comment by K1rakishou** [comment]
Now it's reverted to a much earlier version, before switching to `showDialog`, using `params.awaitButtonClick()?.isPositive() == true` and introducing `resumeOnce` :sweat_smile:

**Comment by jim-daf** [comment]
> Now it's reverted to a much earlier version, before switching to `showDialog`, using `params.awaitButtonClick()?.isPositive() == true` and introducing `resumeOnce` 😅

Yes, that got lost in the rebase.😅 Pushed the showDialog version back, so the controller now uses KurobaComposeDialogController.confirmationDialog passed to dialogFactory.showDialog and reads the result via params.awaitButtonClick()?.isPositive() == true. The resumeOnce wrapper and the unused getString import are gone.

**Review by K1rakishou — APPROVED** [review]
LGTM
